language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: josesegurag90@gmail.com
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
